"""InitI3

Revision ID: 2551ea7427a1
Revises: 33a7322b9970
Create Date: 2023-06-13 17:13:32.125378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2551ea7427a1'
down_revision = '33a7322b9970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
