"""change User, add default 0 to photo_count
Revision ID: 428bdddef9c5
Revises: 33a7322b9970
Create Date: 2023-06-15 09:01:11.856701
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428bdddef9c5'
down_revision = '33a7322b9970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###