"""Rating change

Revision ID: dd1540183b33
Revises: cf2665a1db6b
Create Date: 2023-06-11 12:19:54.947294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1540183b33'
down_revision = 'cf2665a1db6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
