"""Init2

Revision ID: e80f4b9d9a8f
Revises: 79e593e58199
Create Date: 2023-06-10 19:10:45.417861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80f4b9d9a8f'
down_revision = '79e593e58199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
